### ISSUE TITLE
support for sharing text with the links

### ISSUE THREAD

**Issue by Bhupesh-V** [Alex61NN5/easy-social-share-links#6]
It would be nice if we could add a Small piece of Text alongside the link for sharing.

**Comment by Alex61NN5** [comment]
@Bhupesh-V not sure what you mean could you please be more specific? For Twitter and Email sharing you are able to write text before the link!

**Comment by Alex61NN5** [comment]
@Bhupesh-V you can check out a demo of it working here https://easysocialsharelinks.netlify.com

**Comment by Bhupesh-V** [comment]
Ah! :smiley: 
I thought just like in twitter
`https://twitter.com/intent/tweet?url=https://some.link/&text=bla bla bla`
We could have the same functionality of appending text
`&text=bla bla bla`
for linkedin & facebook as well.

**Comment by Alex61NN5** [comment]
As far as I know, Facebook doesn’t allow for you to append text to a link - if you can find an example I will be a happy to include it. I will add a text option for LinkedIn as well.

**Comment by Alex61NN5** [comment]
@Bhupesh-V Feel free to open a pull request for the linkedIn link, should be pretty simple! an example of a linkedIn share link with text is 

`https://www.linkedin.com/shareArticle?mini=true&url=https://google.com&summary=this is some text`
