### ISSUE TITLE
support for reddit

### ISSUE THREAD

**Issue by Bhupesh-V** [Alex61NN5/easy-social-share-links#8]
URL for submitting on reddit looks like this

```https://www.reddit.com/submit?title=Writing%20Functions&url=https%3A//github.com/Bhupesh-V/til/blob/master/CleanCode/cleancode-writing-functions.md```

**Comment by Alex61NN5** [comment]
I will look into this

**Comment by Alex61NN5** [comment]
Closing due to issue being covered here #9
